### ISSUE TITLE
[Feature Request] Multi-account map linking

### ISSUE THREAD

**Issue by 3Stans** [beatmaps-io/beatsaver-main#82] opened 2022-03-13 00:17 UTC
Hello mappers, moppers, lighters, gamers, stans, cats, catgirls, dogs, doggirls, and the rest of you silly little beat saber saberers.

### - Do you work on a map and have perhaps ever decided "man, this is way too much work, oh hey! Lets make this a collab and shovel half the work on someone else!"?

I sure have, and well, when or _if_ we finish that collab, its time to upload and share it with the public who unfortunately gets to gaze upon our holy (and possibly also curse beholding) map that I, and other have put effort in. 

**Okay, now this is where things _may_ get spicy, _who gets to upload it?_**

- For most people, they'll just decide together peacefully (or via standoff) who gets to upload it and that's that. Usually the one who made the map file gets to upload but that's not the case for all. 
- Others, especially if more than 2/3 are involved, may just upload it to a collab account that has been made.
- And for, probably a very small amount, not even sure if anyone actually does this since I haven't checked, may just upload the same map with teeny tiny differences (so they can upload it twice) on both accounts.

The thing is however, with these methods (excluding the last one), sometimes the other participants would like to see  the map on their account as well, for reasons that may consist of but are not limited to; boasting, count accuracy, boasting, peace of mind, boasting, or just simply wanting something to show for it if someone is looking at their account but not the host account. 

### - This is where I think Multi-account map linking would come in hand _(finally getting to the point wow)_

_**How would this work?**_ 
My idea of this would be that after a couple, or a group of mappers have finished collaborating on a map, they can decide who gets to upload it, and the person who gets to upload will be the host of the map who can then invite the other participants and allow them to link the map on their account. The linked map would appear the same as the host map and any other map on the participants account but with any votes going to the host map. 

It could be used to promote maps as well but this is not what I intend the purpose of the feature to be.

The feature could also possibly add an extra little box in the map page with a list of collaborators which are clickable and take you to the pages of each mapper.

_**Okay.... How will it work on the participant's page?**_
The host will have the main controls of the map with just a few extra buttons. If members of the collab wish to have the map on their page, then they do the following:

1. Click an addition "Invite Participant" button (or something along that line)
2. Search for participant mapper name
3. Invite

On the participants side, they have it a little easier and just have to check their alerts tab for an invite. If they have an invite then they have an option to accept or decline, if they choose to accept then the map will appear as the latest upload on their profile but will not re-post to the latest feed on BeatSaver. 

### - What about moderation of this feature?**

- Well first off, participants have the option to accept and decline the invite, declining the invite will simply clear the notif from the alerts tab and the map will show on their account.
- Participants will also have no control over the map on their account, they cannot edit, unpublish, republish, or delete the map from 
BeatSaver, they can only remove the linked map from _their_ account.
- People can also not request to be invited to reduce spam of some kid who wants to try and pass off as helping with the creation of their favorite mod map Up and Down.
- Map hosts can also choose to revoke map linkage by going to the participants page with the linked map and clicking a newly added button labeled "Unlink Map"
- This is separate but their could also be an option for mappers to block other mappers from allowing them to send invites to them.
- As well as a toggle to simply not accept invites. 
- I don't really think these two would be needed but well sometimes the community gets a little crazy.
- Oh and AI made maps that have been deemed certainly made by an AI would not be allowed to be linked.

### - some neat example pictures:
![beatsaver request1](https://user-images.githubusercontent.com/74908347/158039466-da8d60ef-01cf-4de4-bdd2-c96239399b1a.png)

![image](https://user-images.githubusercontent.com/74908347/158039505-57cd5cb0-a1b0-45ac-83b6-460cf0a9b893.png)

Anywho that's basically about it, apologies for any grammatical errors (I swear I did SOME re-reading), thanks for coming to my stantalk

**Comment by Top-Cat** [comment] 2022-03-13 00:30
Duplicate of #43

**Comment by Top-Cat** [comment] 2022-03-13 00:31
I do appreciate a lot of work went into this writeup but it should just be a comment on the existing issue

**Closed by Top-Cat** 2022-03-13 00:30 UTC

**Comment by 3Stans** [comment] 2022-03-13 00:46
I probably should have done more than a quick glance at the issue tabs before writing it.. whoops...
