### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by spectureVR** [beatmaps-io/beatsaver-main#74] opened 2022-02-06 00:19 UTC
So I was thinking about something you could add to the beat saver website.  When you upload a map as a collab you pick the collab option. Then you type in the account of the person you are collabing with. Once you type the username in then a notification would be sent to the person you are collabing with. Then they could verify that that is the collab map. Then once it is uploaded onto beat saver it uploads to both accounts that were in the collab. But it would only upload one version so it's not a duplicate on the main beat saver page.

Just randomly thought of this idea. lmk if this is a feature that might be good for the website on discord. Specture7#0727

**Comment by Top-Cat** [comment] 2022-02-06 14:35
Duplicate of #43

**Closed by Top-Cat** 2022-02-06 14:35 UTC
